### ISSUE TITLE
Can it run on Linux ARM system?

### ISSUE THREAD

**Issue by a514154639** [jimm98y/SharpRTSPtoWebRTC#2]
I had a smooth experience running it on Windows, but it seems to not run well on Linux arm.

**Comment by jimm98y** [comment]
I haven't tried running it on Linux yet. I know it runs well on Windows 11 ARM64, so most likely the issue is not related to ARM64, but to the Linux environment. I'll look into it once I get a new PC that can run Hyper-V/WSL - my current MacOS/Parallels/Windows 11 ARM64 setup makes it difficult to debug anything on Linux.

**Comment by jimm98y** [comment]
I've updated the project and the nuget to the latest version of sipsorcery that includes many bugfixes since the old 6.0.12. Could you please try it out? Also could you please describe what is the current issue on Linux ARM? Do you get crashes, is it slow, is it just not working? Thanks!

**Comment by a514154639** [comment]
> I've updated the project and the nuget to the latest version of sipsorcery that includes many bugfixes since the old 6.0.12. Could you please try it out? Also could you please describe what is the current issue on Linux ARM? Do you get crashes, is it slow, is it just not working? Thanks!

Thank you for your reply. I'll test it again on the Linux ARM system using the latest version. If I encounter any issues, I'll provide you with feedback.
