### ISSUE TITLE
how to play rtsp url of converted files via ffmpeg

### ISSUE THREAD

**Issue by muzlee1992** [jimm98y/SharpRTSPtoWebRTC#4]
hi,I can't play a  rtsp test url of converted files via ffmpeg with this project

**Comment by jimm98y** [comment]
That's quite possible:
1) ffmpeg by itself as far as I know does not stream RTSP. You'll need ffserver which you must compile yourself and that'll allow you to stream RTSP.
2) Streaming offline h264 videos might be problematic because WebRTC does not support b-frames. IP cameras do not commonly use b-frames, which makes it possible to re-stream the RTP "as is" without touching the bitstream. MP4 files, such as movies, often contain b-frames and that would require special configuration of ffmpeg to re-encode the video without using them.

**Comment by jimm98y** [comment]
You can now use https://github.com/jimm98y/SharpRealTimeStreaming to stream RTSP from ffmpeg and then use this project to send it over WebRTC to the web browser.
